admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

admin_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
